version: '2'

services:
  app:
    image: node:6.9.4-alpine
    container_name: node_frontend
    ports:
    - "80:3001"
    volumes:
    - .:/usr/src/app
    environment:
    - NODE_ENV=dev
    - PORT=3001
    command:
      sh -c '
      cd /usr/src/app &&
      /usr/local/bin/node index.js'

  npm-install:
    image: node:6.9.4-alpine
    container_name: npm
    volumes:
      - .:/usr/src/app
    command:
      sh -c '
      cd /usr/src/app &&
      npm install --no-bin-links || npm install --no-bin-links &&
      npm rebuild node-sass --no-bin-links'

  # webpack:
  #   image: node:6.9.4-alpine
  #   container_name: webpack
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     - NODE_ENV=dev
  #   command:
  #     sh -c '
  #     cd /usr/src/app &&
  #     /usr/local/bin/node index.js'

  mocha-watch:
    image: node:6.9.4-alpine
    container_name: mocha-watch
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=test
    command:
      sh -c '
      cd /usr/src/app &&
      /usr/src/app/node_modules/mocha/bin/mocha --watch'

  mocha:
    image: node:6.9.4-alpine
    container_name: mocha
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=test
    command:
      sh -c '
      cd /usr/src/app &&
      /usr/src/app/node_modules/mocha/bin/mocha'

networks:
  default:
    external:
      name: nodeapi_api