export const FETCH_LIVE_RACE_ENTRANTS = 'FETCH_LIVE_RACE_ENTRANTS';
export const ADD_ENTRANT_TO_STREAM_LIST = 'ADD_ENTRANT_TO_STREAM_LIST';
export const REMOVE_ENTRANT_FROM_STREAM_LIST = 'REMOVE_ENTRANT_FROM_STREAM_LIST';